name: "Terraform Apply with JSON Credentials"

on:
  push:
    branches:
      - main

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
      - name: "Checkout code"
        uses: actions/checkout@v3

      - name: "Set up Terraform"
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.0

      - name: "Extract Azure Credentials"
        id: azure_creds
        env:
          AZURE_CREDENTIALS: ${{ secrets.AZURE_CREDENTIALS }}
        run: |
          echo "$AZURE_CREDENTIALS" > azure_credential.json
          export ARM_CLIENT_ID=$(jq -r '.clientId' azure_credential.json)
          export ARM_CLIENT_SECRET=$(jq -r '.clientSecret' azure_credential.json)
          export ARM_TENANT_ID=$(jq -r '.tenantId' azure_credential.json)
          export ARM_SUBSCRIPTION_ID=$(jq -r '.subscriptionId' azure_credential.json)
        shell: bash

      - name: "Azure Login"
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: "Terraform Init"
        run: terraform init

      - name: "Terraform Plan"
        run: terraform plan

      - name: "Terraform Apply"
        run: terraform apply -auto-approve
