name: "Terraform Apply with ARM Environment Variables"

on:
  push:
    branches:
      - main

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
      - name: "Checkout code"
        uses: actions/checkout@v3

      - name: "Set up Terraform"
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.0

      - name: "Extract Azure Credentials"
        id: azure_creds
        env:
          AZURE_CREDENTIALS: ${{ secrets.AZURE_CREDENTIALS }}
        run: |
          echo "$AZURE_CREDENTIALS" > azure_credential.json
          echo "::set-output name=client_id::$(jq -r '.clientId' azure_credential.json)"
          echo "::set-output name=client_secret::$(jq -r '.clientSecret' azure_credential.json)"
          echo "::set-output name=tenant_id::$(jq -r '.tenantId' azure_credential.json)"
          echo "::set-output name=subscription_id::$(jq -r '.subscriptionId' azure_credential.json)"
        shell: bash

      - name: "Azure Login"
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: "Terraform Init"
        env:
          ARM_CLIENT_ID: ${{ steps.azure_creds.outputs.client_id }}
          ARM_CLIENT_SECRET: ${{ steps.azure_creds.outputs.client_secret }}
          ARM_TENANT_ID: ${{ steps.azure_creds.outputs.tenant_id }}
          ARM_SUBSCRIPTION_ID: ${{ steps.azure_creds.outputs.subscription_id }}
        run: terraform init

      - name: "Terraform Plan"
        env:
          ARM_CLIENT_ID: ${{ steps.azure_creds.outputs.client_id }}
          ARM_CLIENT_SECRET: ${{ steps.azure_creds.outputs.client_secret }}
          ARM_TENANT_ID: ${{ steps.azure_creds.outputs.tenant_id }}
          ARM_SUBSCRIPTION_ID: ${{ steps.azure_creds.outputs.subscription_id }}
        run: terraform plan

      - name: "Terraform Apply"
        env:
          ARM_CLIENT_ID: ${{ steps.azure_creds.outputs.client_id }}
          ARM_CLIENT_SECRET: ${{ steps.azure_creds.outputs.client_secret }}
          ARM_TENANT_ID: ${{ steps.azure_creds.outputs.tenant_id }}
          ARM_SUBSCRIPTION_ID: ${{ steps.azure_creds.outputs.subscription_id }}
        run: terraform apply -auto-approve
